#!/usr/bin/env bash
#transfers a file from our client to a server
psshkey="$4"
pfile="$1"
user="$3"
ip="$2"
if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$psshkey" "$pfile" "$user"@"$ip":~/
fi
