#!/usr/bin/env bash
#Install nginx on my server
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.html
sudo service nginx reload
