#!/usr/bin/env bash
#Nginx server so that /redirect_me is redirecting to another page
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School for the win!" > /var/www/html/index.html
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
redirection="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "37i\ $redirection" /etc/nginx/sites-available/default
sudo touch /var/www/html/page404.html
echo -e "Ceci n'est pas une page\n" | sudo tee -a /var/www/html/page404.html
pagerror = "\n\terror_page 404 /page404.html;\n\tlocation = /page404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"
sudo sed -i "37i\ $pagerror" /etc/nginx/sites-available/default
sudo service nginx start
