#!/usr/bin/env bash
# shellcheck disable=SC2154
#Install nginx on my server
sudo apt-get update
sudo apt-get -y install nginx
cabezera="\t\tadd_header X-Served-By '$HOSTNAME';"
sudo sed -i "31i\ $cabezera" /etc/nginx/sites-enabled/default
sudo service nginx reload
sudo service nginx restart
