#!/usr/bin/env bash
# install proxy 
sudo apt-get update -y
sudo apt-get install -y haproxy=1.6\*
echo "frontend 734-frontend
        bind *:80
        default_backend 734-backend
" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "backend 734-backend
        balance roundrobin
        server 734-web-01 34.74.43.63:80 check
        server 734-web-02 35.231.32.10:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
