#!/usr/bin/env bash
# configures the container to fit the above requirements
pkill nginx
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
pkill apache2
sudo -u nginx service nginx restart
